@startuml
'https://plantuml.com/class-diagram
'货运领域模型的类图

class Customer as "客户"
class Cargo as "货物"
class HandingEvent as "处理事件"
class DeliverySpecification as "运送规格"
class DeliveryHistory as "运送历史"
class Carrier as "运输动作"
class Location as "地点"

@enduml